### ISSUE TITLE
What python version I use?

### ISSUE THREAD

**Issue by guanfaqian** [L0SG/seqgan-music#2]
I use python2.7 that tell me music must install in python>3.4.
I use python3.6 that tell me 'cPickle' only exists in python 2.
What version I sholud use?And what should I do when I face these problems？

**Comment by L0SG** [comment]
The project is based on Python 2.7.

From my quick check by creating Python 2.7 anaconda environment, I could download music21 4.1.0 and import it without problem. music21 4.1.0 is the last version that supports Python 2.

[PyPI release history](https://pypi.org/project/music21/#history) shows that the v5 is released this year, and I assume that your Python 2.7 environment tried to download the latest version.

So please try to download music21 4.1.0 version.
