### ISSUE TITLE
How to use new implementation of nll

### ISSUE THREAD

**Issue by VladJamir** [L0SG/seqgan-music#3]
Hi, I'm new to tensorflow, where can I put the new implementation of calculating the nll? I can't seem to find where. Thank you

**Comment by L0SG** [comment]
You would need to implement your own NLL calculation inside [the generator like this](https://github.com/L0SG/seqgan-music/blob/966946fb64edab8f7cfa3554c8e34fced32dec02/generator.py#L149), following the static graph node syntax of the TF. Note that the repo is getting somewhat old in syntax (new versions of TF is starting to prefer the dynamic graph construction similar to PyTorch).
