### ISSUE TITLE
Wasserstein loss in Adversarial training

### ISSUE THREAD

**Issue by VladJamir** [L0SG/seqgan-music#4]
Why is it that wassertein loss was not used in adversarial training?

**Comment by L0SG** [comment]
I had tried various GAN loss terms for the vanilla SeqGAN training (as you could see in the repo), but the Wasserstein loss was not stable & the model could not converge in my case. I've not tried more advanced ones (WGAN-GP, Zero-centered grad penalties, etc) so you might want to try them out.
