### ISSUE TITLE
preprocessing error

### ISSUE THREAD

**Issue by VladJamir** [L0SG/seqgan-music#5]
I was trying to preprocess jazz midi files from another dataset but I got this error
```
Traceback (most recent call last):
  File "preprocessing.py", line 157, in <module>
    seq = a.parsing(data_dir + file)
  File "preprocessing.py", line 59, in parsing
    _part_tuples = self.streaming(event, i, _part_tuples)
  File "preprocessing.py", line 85, in streaming
    oc_idx = self.octave_ref.index(octaves)
ValueError: [5, 4, 5] is not in list
```
What might be the problem? Is it because the content of the jazz midi files is different from the midi files you used?

**Comment by L0SG** [comment]
Sorry for the super late reply. Not entirely sure (have not thoroughly explored the MIDI pipeline), but I believe that for the different dataset, you usually need to re-write some parts of the MIDI preprocessing (the code in this repo is mostly hard-wired for Nottingham).
